### ISSUE TITLE
Do you even know how to git?

### ISSUE THREAD

**Issue by TheComputerGuy96** [shubham23596/camera2#1]
You're stupid AF

And I think you copied Open Camera

**Comment by shubham23596** [comment]
So what do you want for me, please don't use if you don't like it, and stay in your limits who ever you are

**Comment by shubham23596** [comment]
It's my repository, I can put whatever I want please don't interfere in other's business

**Comment by minhng99** [comment]
@shubham23596 you're awesome!

**Comment by TheComputerGuy96** [comment]
This project is dead for a long time (and my opinions have changed over the years) so I might have to close this :frog:
